---
- name: Get certbot-auto
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /usr/local/sbin/certbot-auto
    mode: 0755

- name: Create www-root
  file:
    path: /var/www
    state: directory

- name: Try to get certificate
  ignore_errors: True
  command:
    "/usr/local/sbin/certbot-auto certonly -n --expand --agree-tos --email {{ email }} --webroot -w /var/www {{ item }}"
  with_items:
    - "-d {{ ansible_eth0.ipv4.address }}.nip.io -d wordpress.{{ ansible_eth0.ipv4.address }}.nip.io -d drupal.{{ ansible_eth0.ipv4.address }}.nip.io -d joomla.{{ ansible_eth0.ipv4.address }}.nip.io -d owncloud.{{ ansible_eth0.ipv4.address }}.nip.io -d redmine.{{ ansible_eth0.ipv4.address }}.nip.io -d nodebb.{{ ansible_eth0.ipv4.address }}.nip.io"
    - "-d {{ ansible_fqdn }} -d wordpress.{{ ansible_fqdn }} -d drupal.{{ ansible_fqdn }} -d joomla.{{ ansible_fqdn }} -d owncloud.{{ ansible_fqdn }} -d redmine.{{ ansible_fqdn }} -d nodebb.{{ ansible_fqdn }}"

- name: Symlink certificate
  file:
    src: /etc/letsencrypt/live/{{ item }}/fullchain.pem
    dest: /etc/ssl/private/{{ item }}.crt
    state: link
  with_items:
    - "{{ ansible_fqdn }}"
    - "{{ ansible_eth0.ipv4.address }}.nip.io"

- name: Symlink certificate key
  file:
    src: /etc/letsencrypt/live/{{ item }}/privkey.pem
    dest: /etc/ssl/private/{{ item }}.key
    state: link
  with_items:
    - "{{ ansible_fqdn }}"
    - "{{ ansible_eth0.ipv4.address }}.nip.io"

- name: Reload Nginx
  command: docker restart nginx
  ignore_errors: yes

# Need to also restart web server with hook
- name: Automatically renew cert
  cron:
    name: Lets Encrypt renewal
    hour: 1
    minute: 00
    weekday: 0
    user: root
    job: /usr/local/sbin/certbot-auto renew --quiet --no-self-upgrade

