---
- name: Get certbot-auto
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /usr/local/sbin/certbot-auto
    mode: 0755

- name: Create www-root
  file:
    path: /var/www
    state: directory

- name: Try to get certificate
  ignore_errors: True
  command:
    "/usr/local/sbin/provcfg generate-cert {{ item }} {{ email }}"
  with_items:
    - "{{ ansible_eth0.ipv4.address }}.nip.io"
    - "{{ fqdn|default(ansible_fqdn) }}"

- name: Symlink certificate
  file:
    src: /etc/letsencrypt/live/{{ item }}/fullchain.pem
    dest: /etc/ssl/private/{{ item }}.crt
    state: link
  with_items:
    - "{{ fqdn|default(ansible_fqdn) }}"
    - "{{ ansible_eth0.ipv4.address }}.nip.io"

- name: Symlink certificate key
  file:
    src: /etc/letsencrypt/live/{{ item }}/privkey.pem
    dest: /etc/ssl/private/{{ item }}.key
    state: link
  with_items:
    - "{{ fqdn|default(ansible_fqdn) }}"
    - "{{ ansible_eth0.ipv4.address }}.nip.io"

- name: Reload Nginx
  command: docker restart nginx
  ignore_errors: yes

# Need to also restart web server with hook
- name: Automatically renew cert
  cron:
    name: Lets Encrypt renewal
    hour: 1
    minute: 00
    weekday: 0
    user: root
    job: /usr/local/sbin/certbot-auto renew --quiet --no-self-upgrade

