---
- name: Create required folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/nginx/conf.d
  - /var/www
  - /etc/ssl/certs

- name: Create config files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ item }}"
  with_items:
  - default.conf

- name: Copies in sample index.html
  copy:
    src: index.html
    dest: /var/www/index.html
    force: no

- name: Generate DH file
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048 creates=/etc/ssl/certs/dhparam.pem

- name: Generate self-signed certificate as a placeholder
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=London/L=London/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout "/etc/ssl/certs/{{ ansible_fqdn }}.key" -out "/etc/ssl/certs/{{ ansible_fqdn }}.crt" -extensions v3_ca creates="/etc/ssl/certs/{{ ansible_fqdn }}.crt"

- name: Nginx
  docker:
    name: nginx
    image: nginx
    state: started
    restart_policy: on-failure
    restart_policy_retry: 10
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "/etc/nginx/conf.d:/etc/nginx/conf.d:ro"
    - "/etc/ssl/certs:/etc/ssl/certs:ro"
    - "/var/www:/var/www:ro"
