---
- name: Create required folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/nginx/conf.d
  - /var/www
  - /etc/ssl/private
  - /etc/letsencrypt

- name: Create config files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ item }}"
  with_items:
  - default.conf

- name: Copies in sample index.html
  copy:
    src: index.html
    dest: /var/www/index.html
    force: no

- name: Generate DH file
  command: openssl dhparam -out /etc/ssl/private/dhparam.pem 2048 creates=/etc/ssl/private/dhparam.pem

- name: Generate self-signed certificate as a placeholder
  command: openssl req -new -nodes -x509 -subj "/C=GB/ST=London/L=London/O=IT/CN={{ ansible_fqdn }}" -days 3650 -keyout "/etc/ssl/private/{{ ansible_fqdn }}-snakeoil.key" -out "/etc/ssl/private/{{ ansible_fqdn }}-snakeoil.crt" -extensions v3_ca creates="/etc/ssl/private/{{ ansible_fqdn }}-snakeoil.crt"

- name: Creates symlinks to certificates
  file:
    src: "/etc/ssl/private/{{ ansible_fqdn }}-snakeoil.{{ item }}"
    dest: "/etc/ssl/private/{{ ansible_fqdn }}.{{ item }}"
    state: link
  with_items:
  - crt
  - key

- name: Nginx
  docker:
    name: nginx
    image: nginx
    state: started
    restart_policy: on-failure
    restart_policy_retry: 10
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "/etc/nginx/conf.d:/etc/nginx/conf.d:ro"
    - "/etc/ssl/private:/etc/ssl/private:ro"
    - "/var/www:/var/www:ro"
    - "/etc/letsencrypt:/etc/letsencrypt:ro"
