version: '2'
services:
   nginx:
     build:
        context: .
        dockerfile: Dockerfile.nginx
     restart: always
     ports:
       - 80:80
       - 443:443
     links:
       - api:api
   api:
     build:
        context: .
        dockerfile: Dockerfile.api
     restart: always
     ports:
       - 8080:8080
     links:
      - redis
     volumes:
      - .:/usr/src/app
   worker:
     build:
        context: .
        dockerfile: Dockerfile.worker
     restart: always
     links:
      - redis
     volumes:
      -  .:/usr/src/app
   redis:
     restart: always
     image: redis
