---
- name: Create database user
  command: /usr/local/sbin/mysql_create_db.sh {{ mysql_drupal_user }} {{ mysql_drupal_password }}

- name: Drupal
  docker:
    name: drupal
    image: drupal
    state: started
    restart_policy: always
    net: provisioner
    env:
      MYSQL_USER: "{{ mysql_drupal_user }}"
      MYSQL_PASSWORD: "{{ mysql_drupal_password }}"
      MYSQL_DATABASE: "{{ mysql_drupal_user }}"

- name: Copies in Nginx config
  template:
    src: "../../nginx/templates/{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ role }}-{{ item }}"
    mode: 0644
  with_items:
  - app.conf
  - app.upstream

- name: Reload Nginx
  command: docker exec nginx pkill -HUP -f nginx
