---
- name: MySQL
  docker:
    name: mysql
    image: mariadb
    state: started
    restart_policy: always
    net: provisioner
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    volumes:
    - "/var/lib/mysql:/var/lib/mysql"
    ports:
    - "127.0.0.1:3306:3306"

- name: Copies in createdb script
  copy:
    src: mysql_create_db.sh
    dest: /usr/local/sbin/mysql_create_db.sh
    mode: 0755
