- name: Provisions Grafana (running inside Docker)
  hosts: all
  sudo: yes

  vars:
    - http_port: 3000
    - fqdn: false

  roles:
    - unattended-upgrades
    - docker.ubuntu
    - docker_network
    - nginx
    - mysql
    - grafana
