- name: Provisions Joomla (running inside Docker)
  hosts: all
  become: yes

  roles:
    - unattended-upgrades
    - docker.ubuntu
    - docker_network
    - mysql
    - dns
    - nginx
    - { role: letsencrypt, when: use_ssl }
    - joomla
