- name: Provisions Joomla (running inside Docker)
  hosts: all
  sudo: yes

  vars:
    - mysql_joomla_password:
    - mysql_joomla_user:
    - mysql_root_password:
    - http_port: 8000
  roles:
    - unattended-upgrades
    - docker.ubuntu
    - docker_network
    - mysql
    - nginx
    - joomla
