- name: Provisions Prometheus (running inside Docker)
  hosts: all
  become: yes

  roles:
    - unattended-upgrades
    - docker.ubuntu
    - docker_network
    - dns
    - nginx
    - { role: letsencrypt, when: use_ssl }
    - prometheus
