- name: Provisions WordPress (running inside Docker)
  hosts: all
  sudo: yes

  vars:
    - mysql_root_password:
    - mysql_wordpress_password:
    - mysql_wordpress_user: wordpress
  roles:
    - unattended-upgrades
    - docker.ubuntu
    - mysql
    - wordpress
