---
- name: Create database user
  command: /usr/local/sbin/mysql_create_db.sh {{ mysql_joomla_user }} {{ mysql_joomla_password }}

- name: Joomla
  docker:
    name: joomla
    image: joomla
    state: started
    restart_policy: always
    links:
    - "mysql:mysql"
    env:
      JOOMLA_DB_USER: "{{ mysql_joomla_user }}"
      JOOMLA_DB_PASSWORD: "{{ mysql_joomla_password }}"
      JOOMLA_DB_NAME: "{{ mysql_joomla_user }}"
    ports:
    - "80:80"
