---
- name: Create database user
  command: /usr/local/sbin/mysql_create_db.sh {{ mysql_joomla_user }} {{ mysql_joomla_password }}

- name: Joomla
  docker:
    name: joomla
    image: joomla
    state: started
    hostname: "{{ role }}.{{ ansible_fqdn }}"
    net: provisioner
    restart_policy: always
    env:
      JOOMLA_DB_USER: "{{ mysql_joomla_user }}"
      JOOMLA_DB_PASSWORD: "{{ mysql_joomla_password }}"
      JOOMLA_DB_NAME: "{{ mysql_joomla_user }}"
      JOOMLA_DB_HOST: 'mysql'

- name: Copies in Nginx config
  template:
    src: "../../nginx/templates/{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ role }}-{{ item }}"
    mode: 0644
  with_items:
  - app.conf
  - app.upstream

- name: Reload Nginx
  command: docker exec nginx pkill -HUP -f nginx
