---
- name: Docker Registry
  docker:
    name: docker-registry
    image: registry:2.1
    net: provisioner
    state: reloaded
    restart_policy: always
    volumes:
    - "/usr/local/registry:/var/lib/registry"

- name: Copies in Nginx config
  template:
    src: "../../nginx/templates/{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ role_name }}-{{ item }}"
    mode: 0644
  with_items:
  - app.conf
  - app.upstream
