---
- name: install pip requirements
  pip:
    name={{ item }}
  with_items:
    - dnspython
    - netifaces

- name: Copy in dns script
  copy:
    src: dns_is_configured.py
    dest: /usr/local/bin/dns_is_configured.py
    mode: 0755

- name: Lookup DNS record for hostname
  command: python /usr/local/bin/dns_is_configured.py
  register: dns_lookup

- set_fact: dns_record_exists={{ dns_lookup.stdout }}
