---
- name: MySQL
  docker:
    name: mysql
    image: mariadb
    state: started
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: "{{ mysql_owncloud_password }}"
      MYSQL_DATABASE: owncloud
    volumes:
    - "/var/lib/mysql:/var/lib/mysql"

- name: Owncloud
  docker:
    name: owncloud
    image: owncloud:9-apache
    state: started
    restart_policy: always
    volumes:
    - "/usr/local/owncloud:/var/www/html"
    links:
    - "mysql:mysql"
    ports:
    - "80:80"
