---
- name: Create database user
  command: /usr/local/sbin/mysql_create_db.sh {{ mysql_wordpress_user }} {{ mysql_wordpress_password }}
  args:
    creates: "/root/.created-mysql-database-{{ mysql_wordpress_user }}"

- name: WordPress
  docker:
    name: wordpress
    image: wordpress
    hostname: "{{ role }}.{{ ansible_fqdn }}"
    state: started
    restart_policy: always
    net: provisioner
    env:
      WORDPRESS_DB_USER: "{{ mysql_wordpress_user }}"
      WORDPRESS_DB_PASSWORD: "{{ mysql_wordpress_password }}"
      WORDPRESS_DB_NAME: "{{ mysql_wordpress_user }}"

- name: Copies in Nginx config
  template:
    src: "../../nginx/templates/{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ role }}-{{ item }}"
    mode: 0644
  with_items:
  - app.conf
  - app.upstream

- name: Install zip package
  command: docker exec wordpress {{ item }}
  ignore_errors: yes
  with_items:
    - apt-get update
    - apt-get install -y zip less

- name: Reload Nginx
  command: docker exec nginx pkill -HUP -f nginx
