---
- name: Create database user
  command: /usr/local/sbin/mysql_create_db.sh {{ wordpress_user }} {{ mysql_wordpress_password }}

- name: WordPress
  docker:
    name: wordpress
    image: wordpress
    state: started
    restart_policy: always
    env:
      WORDPRESS_DB_USER: "{{ wordpress_user }}"
      WORDPRESS_DB_PASSWORD: "{{ mysql_wordpress_password }}"
      WORDPRESS_DB_NAME: "{{ wordpress_user }}"
    links:
      - "mysql:mysql"
    ports:
    - "80:80"

- name: Install zip package
  command: docker exec wordpress {{ item }}
  with_items:
    - apt-get update
    - apt-get install -y zip
    - apt-get clean
