---
- name: Copies in sample Prometheus config
  copy:
    src: "prometheus.yml"
    dest: "/usr/local/etc/prometheus.yml"
    mode: 0644

- name: Create htaccess file
  command: htpasswd -bc "/etc/nginx/conf.d/{{ role }}-app.htpasswd" prometheus "{{ prometheus_password }}"
  args:
    creates: "/etc/nginx/conf.d/{{ role }}-app.htpasswd"

- name: Prometheus Push Gateway
  docker:
    name: prometheus-pushgateway
    image: prom/pushgateway
    state: started
    hostname: "{{ role }}-pushgateway.{{ ansible_fqdn }}"
    net: provisioner
    restart_policy: always

- name: Prometheus
  docker:
    name: prometheus
    image: prom/prometheus
    state: started
    hostname: "{{ role }}.{{ ansible_fqdn }}"
    volumes:
    - "/usr/local/etc/prometheus.yml:/etc/prometheus/prometheus.yml"
    net: provisioner
    restart_policy: always

- name: Copies in Nginx config
  template:
    src: "../../nginx/templates/{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ role }}-{{ item }}"
    mode: 0644
  with_items:
  - app.conf
  - app.upstream

- name: Copies in Nginx config for push gateway
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ role }}-{{ item }}"
    mode: 0644
  with_items:
  - pushgateway.conf
  - pushgateway.upstream

- name: Reload Nginx
  command: docker exec nginx pkill -HUP -f nginx
